language: android

components:
    - tools
    - platform-tools
    - build-tools-24.0.2
    - android-24
  licenses:
    - 'android-sdk-license-.+'

jdk:
  - oraclejdk8

script:
  - ./gradlew clean check --stacktrace

branches:
  except:
    - gh-pages

sudo: false

cache:
  directories:
    - $HOME/.gradle
