language: android

android:
  components:
    - build-tools-24.0.2
    - android-24
  licenses:
    - android-sdk-license-.+

jdk:
  - oraclejdk8

before_script:
    - "android update sdk --no-ui --filter build-tools-24.0.2,android-24,extra-android-m2repository"

script:
  - ./gradlew clean check --stacktrace

branches:
  except:
    - gh-pages

sudo: false

cache:
  directories:
    - $HOME/.gradle
