os: osx

osx_image: xcode11.3

script:
  - curl -s "https://get.sdkman.io" | bash
  - source "$HOME/.sdkman/bin/sdkman-init.sh"
  - sdk install java 8.0.242.hs-adpt
  - curl -s https://dl.google.com/android/repository/commandlinetools-mac-6200805_latest.zip -o tools.zip
  - export ANDROID_SDK_ROOT=~/.android
  - mkdir $ANDROID_SDK_ROOT
  - unzip tools.zip -d $ANDROID_SDK_ROOT
  - export PATH=$ANDROID_SDK_ROOT/tools/bin:$PATH
  - avdmanager --list
  - yes | sdkmanager --licenses
  - sdkmanager --install 'platforms;android-28' 'system-images;android-22;default;armeabi-v7a'
  - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  # don't wait for the emulator. Hopefully, it'll start while while we build.
  # if not, we might add some checks here
  - ./gradlew clean build connectedCheck -x checkstyleTest --stacktrace --max-workers=2
  - ./gradlew -p composite build


after_success:
  - ./scripts/deploy.sh

env:
  global:
    # SONATYPE credentials
    - secure: "j6yjcBdSkrQ1FdIIJB9Xv5mZF2HHGDuYsRrAUTA3a22klaYdkgIj2bsmcyDsWutkKqJcsZiV9/MJ/2GhLNoExELk5eWL2a1mq0Fn4CzjVN9JKRYoQbIvbAhvsTFPg+UdMePXSEpG4PgF8HrKzq4HUBuHdNc8P3izaHyqokj/84+YLXFWZ7SBMWS6F5CAAoixfCLQDMCeg4l47qhQBt570ENWz9qME4cRfLBSsYjx/YvCLSva13/vFSrQ2J72VlguYHu7FstYOewd7//Hk5azxhT0KmLzO39MN37o6kpQGz7zNstw56xIJaTNMQ2ClrZhvI3yDpyDP2c/MgPeOeEP6lDdfq08BL1fWjO7njWHKvmieRN7+NsN50o9yNd40fxdgySEKK9B54PVBaUFnYB0GfAVbsGCUNT6zIO42MuN/Slv9471Cr9ZtpBicXYv8kAaKsi0p/dyPDB3X72VQTFnVKna4cZowumxAavJ+ISlewjNs/k+nbB/9J4f0Ax0A60hO51yf41ikjkELdbAAQMeZJHCyuJoGDXz6NKwb+HaVgje1F0jndeKPKG2rTB88mBGAkkS9nSaV5+IeHQnzJRjqjf5ObYkAfsvp8oN1Uz1RHSRHVtkx56gWB24ZZ5gv+SKVZAsCX36JJCzYtIMG150D+2UnA5GrlngJUJvzNRlGnI="
    - secure: "WQLS5VDqdCT0f6MzS0mOS5ug+zJPuDcuiZNL5K21DO9UO3dV36eYgo1dLUVPk6ZB2kBMdr2myiHOafsVC1uJSJ3f2O0oXaOQwIHEtwYN2kCjNossPAhhFS3NFQg/F05Fvx2pxR9hggZe3GDWZOMB4r9Eg2EYF/Jozx3LGt7UwWwT2tl8nVGa009yXlVbDP9XuyqqDM+A2Mosj8ih8xPIUMfyzBlcQDOg8BzIBeyZoaCJfeA4kXOGiWYkC27ZMrlOaqPDmAiSiVSihn3lc4kD0p+RINgl05kjzBQ2P3bb2x4QvQMaQqJ8WCRgAGGlRyyIKcnOvfBjSyC15OwdUMYMJMYam8H9L4FaMFMDMWOUjgKvGU7+uNuu5RyjgSeTHlBa4T2F9Dh585QQxCyIKws5XSX06HTrfIb9AoFhKTYEJCBqiyDIMWPZPT9OFRiOaM5PurJUc287rk+8zgZHn9Tq0yr7eAQ+ILuwM/ugPs3jPshiRSStHNkATV0yhvO6LSwGi3LD2gOsqlTtuh9sXFFw2sYtKJVOjH4pdSa0m9LPDiK5WgrqNa46EkJL9Yrm4hU6wW5za8eVPdjW4/4V3w7PuSt3Munulnxpg+SsXqTMabmokX+A0+FkehSrz9LnS4HGsc1nXkXAbERXbRqAJjxbiGhmCRhEKHEcf0JgkmQ4/AA="
    # BINTRAY_USER=
    - secure: "EFuTczRkVSS4p/sa6DkYo3MQ7k/3FwDXRPE6lc2wFreq4aF6/gPVCoMKd+ZnUzb2J2LnJDcVXZZa0A82GwfZvz/pWlW97qi386lRrxAq3bOKLEDPWlVHG7zg5hMM4MOu6vWIWLk1oQHJavh6ZUOfeKVii83Q5+Wx5l44dhn3toF3eLF77JCVVksCpHbf5Eup5j/E81gFUB84Ne54qQOqWyWsMOor3WFAqfilm/dncUpKl9kR3RpRwtiXpMpX4vajEQsSblOD8uWIJhUYl5KdvlVRx7M3xh7uq9UOtSXJq+D0eA4cFwSyo8y0MOLGKZUXmrFrtp5JFBFvFVuvjBSE2h3tP31K4JswB+t3PjUZU8hhrmpnM6EGtMk44SjjYyb9O16MNRmY+6wEPz4aFKJnZrei2mXtIp9fCoavMR/MzhdjA2CbF4mbL7PVah4OegSDoaUK9/0uvypCQBjF9fuiYry3kETSMsbSDkMo+13TjgW6Dqwxv8Os+cAIuHE7I10ODM6yJwA5y9sxBsfiSdTIo+l799yFmjXt4bKeqXLcOHBMVAcudeU+o3ToPfof/MH0EAQNNTHbBbWaXaYB386q9GA6wAzYA3EhrRaN4qRnCjmBRrZxrycvyl+98jQIsW8eBsgxKvuw840JvmAaACB69tW2LbJvKnSpZ4IXgPXt2as="
    # BINTRAY_API_KEY=
    - secure: "svrT7YrGcMwdMOVbBH7ritFXeNHmvd/+y7ad012f/LynlVwVYUuQCDcdkt9gRYKSMVe7xETLhrYW78j+IJYF739WyN1LIK/jDLTrou4hzEy6UJM6KD14+vNJak69YHz2YSVXEzrF1ofpgZ5OCLj5/u5Py8anILjVG034Omy4OulkHJeJp2TfiGMuD33DCPtK7FaBkuJhJXRNQj5Uw8cbNciZ4kxRYVOuvfHIKZ4miDP5xaWXBGqlj1JkZOeZqjhy0opSn79jrAGB1rVPi4u5EdD0xiffo/FuPbuzx53NFpJm+Xa9B4UVBb7vbCiFcTH6qOFDVEndOtqJzwpHY4OuSsJvdeSO5ehADEz9Kdpcf7ZQWJpYBRCc7RPH7fx/lWIMcYcico2gGKoWZuqgTds03SDF9vyw06orKseAJY3BxYh677KHhPXDY16BZMbQVTmn56NnuekdX2VW75ZxcOjjBbKJWzFnXZzvL7x/01qvhnKOWethbdLqSpNNQ5L7aqAOmL4GygxoRGwjzuF+h2uH1xP5w7Mm7Pr3n0kNstlOEtn7zwTudvc6oZC5bnZUrAFksE50O7ISNZHErxYMvPVFC2Nm4YG6XfQXlp8aX7RqvG36X/ZlW+FXh/ZcBJqmsrSo0oHYiZ4WZ1vGrhMnLFpo7NyyyMexNFg/zl0Xm6f0a4g="
    # GRADLE_PUBLISH_KEY=
    - secure: "OMi22B7t4im3fyE6I0D9B65efhTh4GzMZM/MOig9v3ZnYA8StGRlQUZxLCV++BFLB/kUdMJ8EbC7ahQhQENpOidxEsW4olRlmVgkwsG2ZdeaXoKS1zxmVX6DIlP36Wws+OKLeyWtcfZ+yKehyAQco24uIX7kW+RhM6EvA96XTvobc5c+3qMm0rp5XSzwF5sEdHS7O6+IVvQOcxp0LOmlhDJaX0zY4VSwJS3N0nTfibxwAuLEWmv6XafbabTGUSu/vcJH8KOdUVRUuKAaJwTWV1OunGvQiTAh4gU4Y6nxJetVCYZD0CC/gAd3ky9UlRd+8kg/MtOsUzoF3jeyTdIKSxzi4+LTb2N24k+NsHE9vxR5b94pNPwwzgIp1rOBke+OZUuxw/oxbjBJJBL/GjFSQfyS89DE312uquyhV+B4aTqq7+eMZToNLAszrCm/WIVcXbijBRt9cSRZnmcILr4kq9KhYuq8EZrWn/VDsztja+ds8g4deimczp9gku5dL9v8dD8lmipYWKY3+3Go3cQ08bVjAz8l6RwBf39EFwZWA1GWWtKn7NDOt/ADpKbk4ru3kiRggCD7SMEZQ4+UbjPtW4gwmjyKNFlujIIVsgnMO3tAboNE2y7RIBkcQqHdnacjU9T6dFmwUUZHklRLbdt0gOR4aV0sxmrMd8Yt2ErP33I="
    # GRADLE_PUBLISH_SECRET=
    - secure: "r+ccRmUrI1CBqNQnYmb5IfIwF26fo2X494c0ygqDsASxc921p05TTkmvvxP5/4MRAiTG7I83RTy6crAwSy0aM0cji5aoPigdpStjF7jAgEF/W+BdOQkGPgPafk4D80AZDe1nKn/iJjwwyEZv35vKiIhZHt0VG0Mby/sMxX43vlmZJKOhvl8V+G1oKCuyIk1Fm5uZOD9Y89kPlYEol6TAIpyH4R34N6zFUf+a9K4N5s6hu3IDL6/F5P9VKZWrmAx5rma9omQVicWU8c4k0Qd6gK1so3/5ntQbgZ63jnQ1WFkhMxjk2mPANE7PMtRCRRoRZAokxqT5rJ4XayXCytpDN1W1eI54RQXDBq/TLTc7FuUb1pKui03lVUbVl8e4i8nO9NzQW8ziyZPaknUUNoTxMsSPDwYNVo0kxUi6Ildmru9+zjl3W4T9l8m+9Xs250XxlE1g5baKza9Atyor7xlBP6UWL61Kgv787Fp+F6rGtM8QMFgs++D8JVAAjEn+bOYRtlo/8tvqklUY3DG5AuymfKIZaVSswtftzlLjjuUYvjazb5awfXSV903RbPoGS7EwYoork4cCBxCgQ8gFjLGZa/MIPPAmvnHkatMtmCHXFC8GJjyTUwQjtQKO//onaDOucbfksJYGT4eDtQDRWnhegA2p8B0l36/1s8qIugu7RzM="
    - GRADLE_OPTS="-Xmx4096m"
    - ADB_INSTALL_TIMEOUT=8 # minutes (2 minutes by default)

notifications:
  email: false

branches:
  except:
    - gh-pages

sudo: false

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
