[build]
  base    = "docs/"
  publish = "docs/public/"
  command = "gatsby build --prefix-paths && mkdir -p docs/android && mv public/* docs/android && mv docs public/ && mv public/docs/android/_redirects public && cat README.md | grep -v 'the official docs' > docs/source/essentials/get-started.md'"
[build.environment]
  NPM_VERSION = "6"
